name: List Public Repositories

on:
  workflow_dispatch:
  push:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: List public repos of a user
        run: |
          USERNAME="Philips Software"
          curl -s "https://api.github.com/users/${USERNAME}/repos?per_page=100" \
            | jq -r '.[].name'

